// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdeLUGesIJx4PFXRtJrQ_b73LPPOjiaa8',
    appId: '1:3517983322:web:f58cb1f7d501ae5db08663',
    messagingSenderId: '3517983322',
    projectId: 'book-review-a9ef2',
    authDomain: 'book-review-a9ef2.firebaseapp.com',
    storageBucket: 'book-review-a9ef2.appspot.com',
    measurementId: 'G-QPRBVVGTKQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs_NI2h7qKkpdMhNcDVoqEpuK1ojzVXcQ',
    appId: '1:3517983322:android:b30d57d608a75c6cb08663',
    messagingSenderId: '3517983322',
    projectId: 'book-review-a9ef2',
    storageBucket: 'book-review-a9ef2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWwnBHprCQLufj3jSOE2fcO7Jh5_sFuzc',
    appId: '1:3517983322:ios:36e65ec1d1404ecbb08663',
    messagingSenderId: '3517983322',
    projectId: 'book-review-a9ef2',
    storageBucket: 'book-review-a9ef2.appspot.com',
    iosBundleId: 'com.example.flutterBookReview.RunnerTests',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWwnBHprCQLufj3jSOE2fcO7Jh5_sFuzc',
    appId: '1:3517983322:ios:4d004d48eddbbbc1b08663',
    messagingSenderId: '3517983322',
    projectId: 'book-review-a9ef2',
    storageBucket: 'book-review-a9ef2.appspot.com',
    iosBundleId: 'com.example.flutterBookReview',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdeLUGesIJx4PFXRtJrQ_b73LPPOjiaa8',
    appId: '1:3517983322:web:55f2364d40519a0bb08663',
    messagingSenderId: '3517983322',
    projectId: 'book-review-a9ef2',
    authDomain: 'book-review-a9ef2.firebaseapp.com',
    storageBucket: 'book-review-a9ef2.appspot.com',
    measurementId: 'G-KFY39JCF6E',
  );
}
